<?php
/**
 * ShipStation Authentication Controller Class.
 *
 * Handles the display and management of authentication credentials.
 *
 * @package WC_ShipStation
 */

namespace WooCommerce\Shipping\ShipStation;

use WC_ShipStation_Integration;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Auth_Controller Class
 *
 * Manages authentication data display and WooCommerce API key generation.
 */
class Auth_Controller {

	/**
	 * Option name for storing WooCommerce API key ID.
	 *
	 * @var string
	 */
	const API_KEY_ID_OPTION = 'woocommerce_shipstation_api_key_id';

	/**
	 * Plaintext prefix prepended to every plugin-generated consumer_key.
	 *
	 * Combined with a 35-char `wc_rand_hash()` tail this keeps the total
	 * plaintext at 43 chars, matching WooCommerce's own `ck_<40-hex>` shape
	 * and leaving room inside the hashed `consumer_key char(64)` column and
	 * the `truncated_key char(7)` column without adjustment.
	 *
	 * Surfaced in logs so a support engineer can tell at a glance whether a
	 * key was generated by this plugin or pasted in by hand.
	 *
	 * @since 5.0.8
	 *
	 * @var string
	 */
	const API_KEY_PREFIX = 'ck_wcss_';

	/**
	 * Plaintext prefix prepended to every plugin-generated consumer_secret.
	 *
	 * Stored verbatim in `consumer_secret char(43)`, so this prefix is the
	 * single source of truth for "did this plugin create this row?" — used by
	 * both the modal-side resolver and the rotation sweep to identify our
	 * rows without false-positive risk against merchant-created keys.
	 *
	 * Length budget: prefix (8) + `wc_rand_hash()` tail (35) = 43, exactly
	 * filling `char(43)`. A longer total would silently truncate on insert
	 * in non-strict SQL mode and break authentication.
	 *
	 * @since 5.0.8
	 *
	 * @var string
	 */
	const API_SECRET_PREFIX = 'cs_wcss_';

	/**
	 * Option name for the atomic single-flight lock guarding key generation.
	 *
	 * @since 5.0.8
	 *
	 * @var string
	 */
	const GEN_LOCK_OPTION = 'woocommerce_shipstation_generate_keys_lock';

	/**
	 * Maximum age of the generation lock before it's treated as stale and cleared.
	 *
	 * Generation should take well under a second; 30s is comfortably above any
	 * legitimate runtime and well below any merchant-perceptible wait.
	 *
	 * @since 5.0.8
	 *
	 * @var int
	 */
	const GEN_LOCK_TTL_SECONDS = 30;

	/**
	 * Constructor
	 */
	public function __construct() {
		add_action( 'wp_ajax_shipstation_get_auth_data', array( $this, 'ajax_get_auth_data' ) );
		add_action( 'wp_ajax_shipstation_generate_new_keys', array( $this, 'ajax_generate_new_keys' ) );

		if ( ! is_admin() ) {
			return;
		}

		// phpcs:ignore WordPress.WP.Capabilities.Unknown --- It's native capability from WooCommerce.
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			return;
		}

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- No action taken, just checking tab.
		$is_setting_page           = ! empty( $_GET['tab'] ) && 'integration' === $_GET['tab'];
		$hide_notice               = get_option( 'wc_shipstation_hide_activate_notice', '' );
		$settings_notice_dismissed = get_user_meta( get_current_user_id(), 'dismissed_shipstation-setup_notice', true );

		if ( ! $is_setting_page && ( 'yes' === $hide_notice && $settings_notice_dismissed ) ) {
			return;
		}

		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_scripts' ) );
		add_action( 'admin_footer', array( $this, 'render_auth_modal' ) );
	}

	/**
	 * Enqueue scripts and styles for auth display.
	 */
	public function enqueue_scripts() {
		wp_enqueue_style( 'shipstation-auth-display', plugins_url( 'assets/css/auth-display.css', WC_SHIPSTATION_FILE ), array(), WC_SHIPSTATION_VERSION );

		wp_enqueue_script(
			'shipstation-auth-display',
			WC_SHIPSTATION_PLUGIN_URL . 'assets/js/auth-display.js',
			array(),
			WC_SHIPSTATION_VERSION,
			true
		);

		wp_localize_script(
			'shipstation-auth-display',
			'wc_shipstation_auth_params',
			array(
				'ajax_url'           => admin_url( 'admin-ajax.php' ),
				'nonce'              => wp_create_nonce( 'shipstation_auth_nonce' ),
				'copy_text'          => esc_html__( 'Copied!', 'woocommerce-shipstation-integration' ),
				'show_text'          => esc_html__( 'Show', 'woocommerce-shipstation-integration' ),
				'hide_text'          => esc_html__( 'Hide', 'woocommerce-shipstation-integration' ),
				'error_text'         => esc_html__( 'Error loading authentication data', 'woocommerce-shipstation-integration' ),
				'confirm_text'       => esc_html__( 'Generating new REST API keys will disable your old keys. Connections using them will stop working until you update ShipStation. Continue?', 'woocommerce-shipstation-integration' ),
				'missing_keys_title' => esc_html__( 'REST API keys missing', 'woocommerce-shipstation-integration' ),
				'missing_keys_text'  => esc_html__( 'The REST API keys previously generated for ShipStation are no longer present in WooCommerce. They may have been deleted from WooCommerce → Settings → Advanced → REST API, removed by a security plugin, or lost in a backup restore. ShipStation cannot connect until you generate new keys and update them in ShipStation.', 'woocommerce-shipstation-integration' ),
			)
		);
	}

	/**
	 * Resolve the existing ShipStation API key row for this site without inserting.
	 *
	 * Read-only by contract (SHIPSTN-120): generation happens only through the
	 * explicit user-clicked {@see Auth_Controller::ajax_generate_new_keys()}.
	 *
	 * Returns the row data (key_id + truncated_key) in a single DB query per
	 * path, so the modal can render the truncated_key without a follow-up
	 * lookup. `truncated_key` is the same suffix WC shows in its admin REST API
	 * listing, so it cross-references cleanly for a merchant verifying which
	 * row ShipStation is authenticating against.
	 *
	 * Decision order:
	 *  1. Option set and that row exists → use it (the steady-state path).
	 *  2. Option stale or absent, but a plugin-prefixed row exists → adopt it
	 *     and silently re-point the option. The {@see API_SECRET_PREFIX}
	 *     prefix is a stronger ownership signal than a description match
	 *     ever was: only this plugin inserts rows whose `consumer_secret`
	 *     starts with `cs_wcss_`, so adoption cannot misidentify a
	 *     merchant-created key.
	 *  3. Otherwise → null (caller decides between "show notice" and "first
	 *     time, generate" based on whether the option was previously set).
	 *
	 * This heal lives ONLY on the admin-AJAX path (capability-gated to
	 * `manage_woocommerce`). The REST authentication path deliberately does
	 * not mutate this option so external callers — including Postman tests
	 * against the merchant's endpoints — cannot drift it.
	 *
	 * @return array|null Row data as ['key_id' => int, 'truncated_key' => string], or null if no ShipStation key exists for this site.
	 */
	private function resolve_existing_api_key_row(): ?array {
		$api_key_id = (int) get_option( self::API_KEY_ID_OPTION, 0 );

		if ( $api_key_id > 0 ) {
			$row = $this->get_api_key_row( $api_key_id );
			if ( null !== $row ) {
				return $row;
			}
		}

		$prefixed_row = $this->find_plugin_prefixed_api_key_row();
		if ( null !== $prefixed_row ) {
			update_option( self::API_KEY_ID_OPTION, $prefixed_row['key_id'] );
			return $prefixed_row;
		}

		return null;
	}

	/**
	 * Look up the most recent woocommerce_api_keys row that this plugin
	 * generated, identified by the {@see API_SECRET_PREFIX} on its
	 * `consumer_secret` column.
	 *
	 * `consumer_secret` is stored as plaintext in `char(43)`, so a LIKE
	 * match against the prefix is reliable and locale-independent.
	 * `consumer_key` is stored hashed and cannot be used for the lookup.
	 *
	 * Pre-5.0.8 rows (no prefix) intentionally cannot be matched here: their
	 * ownership is ambiguous from the DB alone, so the legacy
	 * `API_KEY_ID_OPTION` pointer remains the only safe identification for
	 * them.
	 *
	 * @return array|null ['key_id' => int, 'truncated_key' => string] for the most recent plugin-prefixed row, or null if none exists.
	 */
	private function find_plugin_prefixed_api_key_row(): ?array {
		global $wpdb;

		$like = $wpdb->esc_like( self::API_SECRET_PREFIX ) . '%';

		$row = $wpdb->get_row( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
			$wpdb->prepare(
				"SELECT key_id, truncated_key FROM {$wpdb->prefix}woocommerce_api_keys WHERE consumer_secret LIKE %s ORDER BY key_id DESC LIMIT 1",
				$like
			),
			ARRAY_A
		);

		if ( ! is_array( $row ) || empty( $row['key_id'] ) ) {
			return null;
		}

		return array(
			'key_id'        => (int) $row['key_id'],
			'truncated_key' => is_string( $row['truncated_key'] ) ? $row['truncated_key'] : '',
		);
	}

	/**
	 * Fetch the woocommerce_api_keys row data needed by the modal for a known
	 * key_id, or null when the row no longer exists (deleted externally).
	 *
	 * Returning the row in a single query removes the previous two-query
	 * pattern (existence check + separate truncated_key lookup).
	 *
	 * @param int $api_key_id The API key ID.
	 *
	 * @return array|null ['key_id' => int, 'truncated_key' => string], or null if the row is missing.
	 */
	private function get_api_key_row( int $api_key_id ): ?array {
		global $wpdb;

		$row = $wpdb->get_row( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
			$wpdb->prepare(
				"SELECT key_id, truncated_key FROM {$wpdb->prefix}woocommerce_api_keys WHERE key_id = %d",
				$api_key_id
			),
			ARRAY_A
		);

		if ( ! is_array( $row ) || empty( $row['key_id'] ) ) {
			return null;
		}

		return array(
			'key_id'        => (int) $row['key_id'],
			'truncated_key' => is_string( $row['truncated_key'] ) ? $row['truncated_key'] : '',
		);
	}

	/**
	 * Return the first admin user ID to assign as the API key owner.
	 *
	 * WooCommerce REST auth runs every request under the key owner's capabilities.
	 * Tying the key to the triggering user is unsafe: that user may later lose their
	 * role or be deleted, causing every REST endpoint to return rest_forbidden.
	 * Using the first administrator keeps the key stable.
	 *
	 * @return int
	 */
	private function get_admin_user_id(): int {
		// Try site-level administrators first (works on single site and multisite).
		$admins = get_users(
			array(
				'role'        => 'administrator',
				'number'      => 1,
				'orderby'     => 'ID',
				'order'       => 'ASC',
				'fields'      => 'ID',
				'count_total' => false,
			)
		);

		if ( ! empty( $admins ) ) {
			return (int) $admins[0];
		}

		// On multisite, fall back to the first network super admin.
		// get_users() only queries site-level roles, so super admins who haven't
		// been explicitly added to this site won't appear in the query above.
		if ( is_multisite() ) {
			$super_admins = get_super_admins();
			$user         = ! empty( $super_admins ) ? get_user_by( 'login', $super_admins[0] ) : false;

			if ( $user ) {
				return $user->ID;
			}
		}

		return get_current_user_id();
	}

	/**
	 * Generate new WooCommerce REST API credentials.
	 *
	 * @return array API credentials.
	 */
	private function generate_api_credentials(): array {
		global $wpdb;

		// 8-char prefix + 35-char random tail = 43 chars total, exactly
		// matching WC's default key shape and fitting `consumer_secret char(43)`.
		$consumer_key    = wc_rand_hash( self::API_KEY_PREFIX, 35 );
		$consumer_secret = wc_rand_hash( self::API_SECRET_PREFIX, 35 );
		$table_name      = $wpdb->prefix . 'woocommerce_api_keys';

		$data = array(
			'user_id'         => $this->get_admin_user_id(),
			'description'     => __( 'ShipStation Integration', 'woocommerce-shipstation-integration' ),
			'permissions'     => 'read_write',
			'consumer_key'    => wc_api_hash( $consumer_key ),
			'consumer_secret' => $consumer_secret,
			'truncated_key'   => substr( $consumer_key, -7 ),
		);

		$result = $wpdb->insert(
			$table_name,
			$data,
			array(
				'%d',
				'%s',
				'%s',
				'%s',
				'%s',
				'%s',
			)
		);

		if ( false === $result || $wpdb->insert_id <= 0 ) {
			// Redact any plaintext plugin-generated secret echoed back in the
			// MySQL error (e.g. "Duplicate entry 'cs_wcss_…' for key …") before
			// it lands in debug.log.
			$safe_db_error = (string) preg_replace( '/(c[ks]_wcss_)\S+/', '$1[redacted]', (string) $wpdb->last_error );
			Logger::error( 'Failed to insert API key into database. DB error: ' . $safe_db_error );
			return array();
		}

		$api_key_id = $wpdb->insert_id;
		update_option( self::API_KEY_ID_OPTION, $api_key_id );

		return array(
			'consumer_key'    => $consumer_key,
			'consumer_secret' => $consumer_secret,
			'api_key_id'      => $api_key_id,
		);
	}

	/**
	 * Get the auth metadata visible on every dialog open — site URL and the
	 * legacy XML auth key.
	 *
	 * REST API credentials are intentionally not included: their plaintext is
	 * unrecoverable once stored (consumer_key is hashed in the keys table) and
	 * surfacing them on read would require regenerating, which is the bug
	 * fixed in SHIPSTN-120. Plaintext is only returned by the explicit
	 * generate-new-keys flow.
	 *
	 * @return array Authentication metadata.
	 */
	private function get_auth_data(): array {
		// Read the option BEFORE the resolver, since the drift-heal may
		// overwrite it and mask the first-time case below.
		$had_key_option = (bool) get_option( self::API_KEY_ID_OPTION, false );

		$resolved_row = $this->resolve_existing_api_key_row();
		$keys_exist   = null !== $resolved_row;

		/*
		 * JS distinguishes three states:
		 * - keys_exist: row in DB, plaintext already seen (after-view).
		 * - keys_existed_but_missing: option set but row gone (deleted externally) → warn merchant.
		 * - first_time: never generated → JS auto-triggers generate-new-keys.
		 */
		$keys_existed_but_missing = ! $keys_exist && $had_key_option;
		$first_time               = ! $keys_exist && ! $had_key_option;

		return array(
			'site_url'                 => $this->get_store_url_for_shipstation(),
			'auth_key'                 => WC_ShipStation_Integration::$auth_key,
			'keys_exist'               => $keys_exist,
			'keys_existed_but_missing' => $keys_existed_but_missing,
			'first_time'               => $first_time,
			'truncated_key'            => $keys_exist ? $resolved_row['truncated_key'] : '',
		);
	}

	/**
	 * Resolve the URL the merchant should paste into ShipStation's "Store URL"
	 * field. With WPCOM transport active and the site Jetpack-connected, that's
	 * the WPCOM proxy entry point; otherwise it's the merchant's own site URL.
	 *
	 * The proxy URL routes ShipStation traffic via WordPress.com (which signs
	 * each call with the blog token before forwarding to the merchant), so a
	 * merchant whose site is firewalled / behind a security plugin only needs
	 * to allowlist `*.wordpress.com` rather than reverse-engineer their host's
	 * blocking layer. The plugin's REST gate accepts both transports
	 * identically; the URL surfaced in the modal decides which one ShipStation
	 * actually uses.
	 *
	 * @since 5.0.5
	 *
	 * @return string Site or proxy URL, without a trailing slash.
	 */
	private function get_store_url_for_shipstation(): string {
		if ( Features::is_wpcom_transport_enabled() ) {
			$connection = Main::instance()->get_wpcom_connection();
			if ( null !== $connection && $connection->is_connected() ) {
				$blog_id = $connection->get_blog_id();
				if ( null !== $blog_id ) {
					return sprintf(
						'https://public-api.wordpress.com/wpcom/v2/sites/%d/shipstation',
						$blog_id
					);
				}
			}
		}

		return home_url();
	}

	/**
	 * Generate new API keys, sweeping older plugin-generated rows.
	 *
	 * Generation runs first; only after the new INSERT succeeds do we sweep
	 * the older rows. A failed insert must not leave the merchant with zero
	 * valid credentials.
	 *
	 * The sweep is keyed on the {@see API_SECRET_PREFIX} prefix so it can
	 * only ever delete rows this plugin created. Two real-world consequences
	 * of that scoping:
	 *
	 *  - A merchant-created key that happens to share our description (e.g.
	 *    someone manually added a row labelled "ShipStation Integration") is
	 *    safe — its secret has no `cs_wcss_` prefix.
	 *  - Pre-5.0.8 plugin-generated rows are also spared, because they pre-date
	 *    the prefix. That is deliberate: the merchant may still have
	 *    ShipStation configured against one of those rows, and deleting it
	 *    would break their live connection. The merchant can revoke them
	 *    manually from WooCommerce → Settings → Advanced → REST API once
	 *    they've migrated to the new prefixed credentials.
	 *
	 * Concurrency contract: callers MUST hold {@see acquire_generation_lock()}.
	 * Without the lock, two concurrent invocations can each insert a prefixed
	 * row and then have their sweeps delete each other's row, leaving the
	 * merchant with plaintext credentials pointing at a deleted key_id. The
	 * only production caller, {@see ajax_generate_new_keys()}, acquires the
	 * lock before invoking this method; any new caller (CLI, REST diagnostic,
	 * scheduled task) must do the same.
	 *
	 * @return array New API credentials.
	 */
	private function generate_new_keys(): array {
		$new_credentials = $this->generate_api_credentials();

		if ( ! empty( $new_credentials['api_key_id'] ) ) {
			$this->delete_orphan_api_keys( (int) $new_credentials['api_key_id'] );
		}

		return $new_credentials;
	}

	/**
	 * Delete every plugin-generated woocommerce_api_keys row except the one to keep.
	 *
	 * Identifies plugin-generated rows by the {@see API_SECRET_PREFIX} prefix
	 * on the plaintext `consumer_secret` column. This is the only column we
	 * control that's both stored verbatim (unlike `consumer_key`, which is
	 * hashed) and unambiguous (unlike `description`, which a merchant or a
	 * past locale could have produced).
	 *
	 * @param int $keep_key_id The key_id to preserve (the freshly inserted row).
	 */
	private function delete_orphan_api_keys( int $keep_key_id ): void {
		global $wpdb;

		$like = $wpdb->esc_like( self::API_SECRET_PREFIX ) . '%';

		$result = $wpdb->query( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
			$wpdb->prepare(
				"DELETE FROM {$wpdb->prefix}woocommerce_api_keys WHERE consumer_secret LIKE %s AND key_id <> %d",
				$like,
				$keep_key_id
			)
		);

		if ( false === $result ) {
			Logger::error( 'Failed to sweep stale ShipStation API keys. DB error: ' . $wpdb->last_error );
		}
	}

	/**
	 * AJAX handler for getting authentication data.
	 */
	public function ajax_get_auth_data() {
		if ( ! isset( $_POST['nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['nonce'] ) ), 'shipstation_auth_nonce' ) ) {
			wp_die( esc_html__( 'Security check failed', 'woocommerce-shipstation-integration' ) );
		}

		// phpcs:ignore WordPress.WP.Capabilities.Unknown --- It's native capability from WooCommerce.
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			wp_die( esc_html__( 'You do not have sufficient permissions.', 'woocommerce-shipstation-integration' ) );
		}

		wp_send_json_success( $this->get_auth_data() );
	}

	/**
	 * Atomically acquire the generation lock, or return false if another
	 * request already holds it.
	 *
	 * Two near-simultaneous dialog opens (browser preconnect, monitoring tool,
	 * a second admin tab) can both observe `first_time === true` and both
	 * POST to ajax_generate_new_keys. Without this lock, both inserts succeed,
	 * both sweeps then delete the OTHER request's row, and the plaintext
	 * shown in tab A points at a row tab B already deleted — ShipStation
	 * silently fails to connect.
	 *
	 * Implemented via add_option(), which is atomic at the DB level (UNIQUE
	 * constraint on option_name) and works without an object cache. The
	 * stale-clear path is also race-safe: if two requests both observe an
	 * expired lock and both delete + add_option(), the UNIQUE constraint
	 * still picks exactly one winner.
	 *
	 * `add_option()` returns false for any failure — option already exists
	 * (genuine contention) or a transient DB write error. After a false
	 * return we re-read the option to disambiguate: an existing lock value
	 * means real contention, while no value means the write failed and the
	 * caller can retry on the merchant's next attempt. The DB-error case is
	 * surfaced via the logger so support can trace it without confusing the
	 * merchant.
	 *
	 * @return bool True if the lock was acquired by this request.
	 */
	private function acquire_generation_lock(): bool {
		global $wpdb;

		$existing = (int) get_option( self::GEN_LOCK_OPTION, 0 );
		if ( $existing > 0 && ( time() - $existing ) > self::GEN_LOCK_TTL_SECONDS ) {
			delete_option( self::GEN_LOCK_OPTION );
		}

		if ( add_option( self::GEN_LOCK_OPTION, time(), '', 'no' ) ) {
			return true;
		}

		// add_option() returned false. Re-read to tell "lock genuinely held by
		// a sibling request" from "transient DB write error". Only the former
		// is a normal/expected outcome.
		if ( false === get_option( self::GEN_LOCK_OPTION, false ) ) {
			Logger::error( 'Failed to acquire ShipStation generation lock (no lock row present after add_option). DB error: ' . (string) $wpdb->last_error );
		}

		return false;
	}

	/**
	 * Release the generation lock.
	 */
	private function release_generation_lock(): void {
		delete_option( self::GEN_LOCK_OPTION );
	}

	/**
	 * AJAX handler for generating new API keys.
	 */
	public function ajax_generate_new_keys() {
		if ( ! isset( $_POST['nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['nonce'] ) ), 'shipstation_auth_nonce' ) ) {
			wp_die( esc_html__( 'Security check failed', 'woocommerce-shipstation-integration' ) );
		}

		// phpcs:ignore WordPress.WP.Capabilities.Unknown --- It's native capability from WooCommerce.
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			wp_die( esc_html__( 'You do not have sufficient permissions.', 'woocommerce-shipstation-integration' ) );
		}

		if ( ! $this->acquire_generation_lock() ) {
			wp_send_json_error(
				array(
					'message' => __( 'Another request is currently generating REST API keys. Please refresh the page and try again.', 'woocommerce-shipstation-integration' ),
				)
			);
			return;
		}

		try {
			$new_credentials = $this->generate_new_keys();
		} finally {
			$this->release_generation_lock();
		}

		if ( empty( $new_credentials ) ) {
			wp_send_json_error( array( 'message' => __( 'Failed to generate API credentials. Please try again or contact your hosting provider if the issue persists.', 'woocommerce-shipstation-integration' ) ) );
			return;
		}

		$auth_data = array(
			'consumer_key'    => $new_credentials['consumer_key'],
			'consumer_secret' => $new_credentials['consumer_secret'],
			'auth_key'        => WC_ShipStation_Integration::$auth_key,
			'site_url'        => $this->get_store_url_for_shipstation(),
		);

		wp_send_json_success( $auth_data );
	}

	/**
	 * Render the authentication modal HTML.
	 */
	public function render_auth_modal() {
		wc_get_template(
			'auth-modal.php',
			array(),
			'',
			WC_SHIPSTATION_ABSPATH . 'templates/'
		);
	}

	/**
	 * Get the "View Authentication Data" button HTML.
	 *
	 * @return string Button HTML.
	 */
	public static function get_auth_button_html(): string {
		return sprintf(
			'<button type="button" id="shipstation-view-auth" class="button button-primary">%s</button>',
			esc_html__( 'View Authentication Data', 'woocommerce-shipstation-integration' )
		);
	}
}
